### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 2774** [ajanata/PretendYoureXyzzy#164] opened 2018-02-17 04:09 UTC
Is there a way you can transfer hosts??

**Comment by ajanata** [comment] 2018-02-17 18:31
Do you mean for the servers I run? Why? The hardware is more than sufficient, and it's hardware I co-own in a datacenter. There's no compelling reason for me to spend more money out-of-pocket to move the servers somewhere else, when what currently exists is more than powerful enough. Any issues that exist are caused by the PYX software itself, and moving hosts wouldn't resolve that. I'm going to try to spend some time in the next few weeks addressing some of the problems, but this code was written 6 years ago and was never planned on having to scale this much, so honestly I'm surprised it works as well as it does.

**Comment by ajanata** [comment] 2018-02-17 18:31
Closing this since this isn't actually related to the software.

**Closed by ajanata** 2018-02-17 18:31 UTC

**Comment by 2774** [comment] 2018-02-27 10:13
I'm sorry, i wrote that wrong. i meant is there a way to switch the host role onto someone else. My friend wanted me to create a game for her since she doesn't know how and i wanted her to have the host role to host the game so i could leave. My apologies. @ajanata

**Comment by ajanata** [comment] 2018-02-27 22:04
It will automatically transfer the host to the next person in the user list, so if she joins the game immediately after you and before anybody else does (best accomplished by temporarily using a password), it'll work fine. There is no way to manually designate a new host.
